---
author: Jayani P. Gamage
qualifications: B.Sc. (Hons) in Statistics
position: PhD student
www: jayanilakshika.netlify.app
email: jayani.piyadigamage@monash.edu
phone: +61 4 5229 8443
#signature: sigfile.png
address:
  - Editors
  - Journal of Computational and Graphical Statistics
opening: "Dear Professor Yuguo Chen and Professor Laura M. Sangalli,"
closing: "Sincerely"
linestretch: 1.4
format: letter-pdf
---

Please consider our manuscript entitled *“Looking at Non-Linear Dimension Reductions as Models in the Data Space”* for publication in the *Journal of Computational and Graphical Statistics*.

Non-linear dimension reduction (NLDR) techniques, such as tSNE and UMAP, are widely used for producing low-dimensional representations of high-dimensional data. While these methods can provide concise and powerful summaries, they also have the potential to exaggerate random patterns or create misleading structures. Different NLDR methods and different choices of hyper-parameters often produce wildly varying representations from the same data, leaving analysts with difficult decisions about which, if any, of these views are accurate.

Our manuscript introduces an approach that treats NLDR outputs as models and visualizes them directly in the original high-dimensional space using tours (movies of linear projections). This allows analysts to assess how well the NLDR model fits across all subspaces, identify mismatches, and compare the summaries provided by different methods. The approach we describe offer a new, visually interpretable way to diagnose NLDR results and support more trustworthy use of these techniques in high-dimensional data analysis.

We believe that this work is a strong fit for *JCGS*, given the journal’s focus on innovative statistical graphics, computational methodology, and tools that help analysts better understand high-dimensional data. Our approach combines statistical modeling, dynamic visualization, and interactive diagnostics, contributing to the journal’s mission of advancing the use of computation and graphics in statistical practice.

Thank you for the consideration of this manuscript. We believe that it is a good fit for the Journal of Computational and Graphical Statistics.
