## This script is to compare the prediction approaches...

# Load libraries
library(tidyr)
library(dplyr)
library(tibble)
library(rsample)
library(readr)
library(ggplot2)
library(conflicted)
library(quollr)
library(ggthemes)
library(RColorBrewer)
library(patchwork)

library(Rtsne)
library(umap) #predict for uwot not working
library(phateR)

conflicts_prefer(umap::umap)
conflicts_prefer(dplyr::filter)

library(reticulate)
use_python("~/miniforge3/envs/pcamp_env/bin/python")
use_condaenv("pcamp_env")

#reticulate::source_python(paste0(here::here("R/function_scripts/Fit_PacMAP_code.py")))
#reticulate::source_python(paste0(here::here("R/function_scripts/Fit_TriMAP_code.py")))

#source(here::here("R/nldr_code.R"), local = TRUE)

## Read the 2NC7 data
d_2NC7 <- read_rds(here::here("data/two_nonlinear/two_non_linear_diff_shaped_close_clusters_data.rds"))

################################################################################

## Run UMAP on the whole data (training + test), and save result
# Create a config list with the parameters matching layout for main paper
# which happen to be the defaults, actually.
# a better UMAP layout can be generated using n_neighbors = 50, min_dist <- 0.9
# set.seed(20240110)
# #n_neighbors <- 15
# #min_dist <- 0.1
# umap_config <- umap.defaults
# #umap_config$n_neighbors <- n_neighbors      # Set the number of neighbors
# #umap_config$n_components <- 2    # Set the number of output dimensions (typically 2 or 3)
# #umap_config$min_dist <- min_dist
#
# UMAP_fit <- umap(d_2NC7, config = umap_config)
#
# UMAP_d_2NC7 <- UMAP_fit$layout |>
#   as_tibble()
# names(UMAP_d_2NC7) <- c("UMAP1", "UMAP2")
#
# # check result
# ggplot(UMAP_d_2NC7, aes(UMAP1, UMAP2)) +
#   geom_point() +
#   theme_few() +
#   theme(aspect.ratio = 1)
#
# write_rds(UMAP_d_2NC7, file = "data/two_nonlinear/two_non_linear_diff_shaped_close_clusters_umap_n-neigbors_15_min-dist_0.1.rds")
# save(UMAP_fit, file="data/two_nonlinear/UMAP_fit.rda")

## Data: generated by code above
UMAP_d_2NC7 <- read_rds("data/two_nonlinear/two_non_linear_diff_shaped_close_clusters_umap_n-neigbors_15_min-dist_0.1.rds")
load("data/two_nonlinear/UMAP_fit.rda")

## To split the layout and the data, ID needed for this
set.seed(20240110)
UMAP_d_2NC7 <- UMAP_d_2NC7 |>
  mutate(ID = row_number()) |>
  mutate(cluster = if_else(ID <= 1000, "cluster1", "cluster2"))

split <- initial_split(UMAP_d_2NC7, prop = 0.7, strata = cluster)
UMAP_d_2NC7_tr <- training(split)
UMAP_d_2NC7_ts <- testing(split)

d_2NC7 <- d_2NC7 |>
  mutate(ID = row_number())

d_2NC7_tr <- d_2NC7 |>
  filter(ID %in% split$in_id)
d_2NC7_ts <- d_2NC7 |>
  filter(!(ID %in% split$in_id))

## Predict the test set with UMAP model, and save result
#
# UMAP_d_2NC7_ts_pred <- predict(UMAP_fit, d_2NC7_ts[, 1:7]) |>
#   as_tibble()
#
# names(UMAP_d_2NC7_ts_pred) <- c("UMAP1", "UMAP2")
# write_rds(UMAP_d_2NC7_ts_pred, file="data/two_nonlinear/two_non_linear_diff_shaped_close_clusters_umap_predict_test.rds")

# Read predictions, generated by code above
UMAP_d_2NC7_ts_pred <- read_rds("data/two_nonlinear/two_non_linear_diff_shaped_close_clusters_umap_predict_test.rds")

### quollr on training data using UMAP layout

## Fit the model, fit_highd_model needs consecutive IDs
## OOOH, don't like the re-making ID here, this can create problems
## Maybe keep to IDs, call one ID_tr and ID_ts
d_2NC7_tr <- d_2NC7_tr |>
  rename(ID_orig = ID) |>
  mutate(ID = row_number()) |>
  select(x1:x7, ID, ID_orig)
d_2NC7_ts <- d_2NC7_ts |>
  rename(ID_orig = ID) |>
  mutate(ID = row_number()) |>
  select(x1:x7, ID, ID_orig)

UMAP_d_2NC7_tr <- UMAP_d_2NC7_tr |>
  rename(ID_orig = ID) |>
  mutate(ID = row_number()) |>
  select(UMAP1, UMAP2, ID, ID_orig, cluster)
UMAP_d_2NC7_ts <- UMAP_d_2NC7_ts |>
  rename(ID_orig = ID) |>
  mutate(ID = row_number()) |>
  select(UMAP1, UMAP2, ID, ID_orig, cluster)

num_bins_x_2NC7 <- 54

algo_obj_2NC7 <- fit_highd_model(
  highd_data = d_2NC7_tr[, 1:8],
  nldr_data = UMAP_d_2NC7_tr[, 1:3],
  b1 = num_bins_x_2NC7,
  q = 0.1,
  hd_thresh = 0)

umap_2NC7_scaled <- algo_obj_2NC7$nldr_scaled_obj$scaled_nldr
tr_from_to_df_2NC7 <- algo_obj_2NC7$trimesh_data
df_bin_centroids_2NC7 <- algo_obj_2NC7$model_2d
df_bin_2NC7 <- algo_obj_2NC7$model_highd
hex_grid <- algo_obj_2NC7$hb_obj$hex_poly
counts_df <- algo_obj_2NC7$hb_obj$std_cts

## Predict positions using quollr

d_2NC7_ts_qpred <- predict_emb(highd_data = d_2NC7_ts[,1:8],
                           model_highd = df_bin_2NC7,
                           model_2d = df_bin_centroids_2NC7)

## Comparison 1: Compare train vs test UMAP positions (remember trained on all this data, so should look similar)
## Note original NLDR scale

d <- bind_rows(UMAP_d_2NC7_tr, UMAP_d_2NC7_ts) |>
  mutate(type = factor(c(rep("train", NROW(UMAP_d_2NC7_tr)),
                  rep("test", NROW(UMAP_d_2NC7_ts)))))
ggplot(d,
       aes(x = UMAP1, y = UMAP2, colour = type)) +
  geom_point(alpha = 0.5, size = 1) +
  scale_color_brewer("", palette = "Paired", direction = -1) +
  theme_few() +
  theme(aspect.ratio = 1)

## Comparison 2: Compare UMAP true test positions vs predicted positions

ggplot(UMAP_d_2NC7_ts,
       aes(x = UMAP1, y = UMAP2)) +
  geom_point(alpha = 0.5, colour = "#d0d1e6", size = 0.5) +
  geom_point(data = UMAP_d_2NC7_ts_pred, aes(
    x = UMAP1, y = UMAP2
  ), alpha = 0.5, colour = "#045a8d", size = 0.5) +
  theme_few() +
  theme(aspect.ratio = 1)

### DC: Are you sure the rows are returned in the same order by the UMAP prediction?

d <- bind_cols(UMAP_d_2NC7_ts, UMAP_d_2NC7_ts_pred) |>
  rename(true_UMAP1 = `UMAP1...1`,
         true_UMAP2 = `UMAP2...2`,
         pred_UMAP1 = `UMAP1...5`,
         pred_UMAP2 = `UMAP2...6`) #|>
  #pivot_longer(c(true_UMAP1, true_UMAP2, pred_UMAP1, pred_UMAP2),
  #             names_to = "type", values_to = "position") |>
  #separate(type, into = c("type", "coord")) |>
  #pivot_wider(names_from = coord, values_from = position)
# Probably could have used bind_rows to make this easier

#ggplot(d, aes(UMAP1, UMAP2, colour = type)) +
#  geom_point() +
#  scale_colour_brewer("", palette = "Paired", direction = -1) +
#  theme_few() +
#  theme(aspect.ratio = 1)

p1 <- ggplot(d, aes(true_UMAP1, pred_UMAP1)) +
  geom_abline(intercept = 0, slope = 1) +
  geom_point(alpha=0.5) +
  coord_equal() +
  theme_few()
p2 <- ggplot(d, aes(true_UMAP2, pred_UMAP2)) +
  geom_abline(intercept = 0, slope = 1) +
  geom_point(alpha=0.5) +
  coord_equal() +
  theme_few()
p1 + p2 + plot_layout(ncol=2)

## Comparison 3: Compare quollr positions vs UMAP positions

d_2NC7_ts_qpred_scaled <- gen_scaled_data(nldr_data = UMAP_d_2NC7_ts)$scaled_nldr

ggplot(d_2NC7_ts_qpred_scaled,
       aes(x = UMAP1, y = UMAP2)) +
  geom_point(alpha = 0.5, colour = "#d0d1e6", size = 0.5) +
  geom_point(data = d_2NC7_ts_qpred, aes(
    x = pred_emb_1, y = pred_emb_2
  ), alpha = 0.5, colour = "#045a8d", size = 0.5) +
  theme_few() +
  theme(aspect.ratio = 1)


################################################################################

## Simulate new test data (within the domain)

set.seed(202401111)

gen_curv1_3d <- function(n = 100) {

  x1 <- runif(n, 0, 2)
  x2 <- runif(n, 0, 3)
  x3 <- -(x1^3 + x2)
  x4 <- runif(n, 0, 1)

  df2 <- tibble(
    x1 = x1,
    x2 = x2,
    x3 = x3,
    x4 = x4
  )

  df2

}

gen_curv2_3d <- function(n) {
  a <- 3 * pi * stats::runif(n = n, min = -0.5, max = 0)
  x1 <- sin(a)
  x2 <- 2.0 * stats::runif(n = n)
  x3 <- sign(a) * (cos(a) - 1)
  x4 <- cos(a)

  df <- tibble(
    x1 = x1,
    x2 = x2,
    x3 = x3,
    x4 = x4
  )

  df
}

# Simulate some s_curve_noise

sample_size <- 300
curve2 <- gen_curv1_3d(n = sample_size)
langevitour(curve2)

curve1 <- gen_curv2_3d(n = sample_size)

# Apply an offset to one of the clusters to create a distance between them
offset <- c(1.5, 3.3, 2, 1.5)  # Adjust these values to set the desired distance
curve2 <- sweep(curve2, 2, offset, "+")

df <- bind_rows(
  curve1,
  curve2
)

df$x5 <- runif(NROW(df), -0.02, 0.02)
df$x6 <- runif(NROW(df), -0.1, 0.1)
df$x7 <- runif(NROW(df), -0.01, 0.01)

# tSNE simulate new test data and then compare training vs new predicted test

## To read tSNE for training data
tsne_2NC7 <- read_rds("data/two_nonlinear/two_non_linear_diff_shaped_close_clusters_tsne_perplexity_47.rds")

tSNE_training <- tsne_2NC7 |>
  filter(ID %in% UMAP_d_2NC7_tr$ID)

## tSNE
perplexity <- 47

tSNE_fit <- df |>
  dplyr::select(where(is.numeric)) |>
  Rtsne::Rtsne(perplexity = perplexity,
               pca = FALSE)

## Loss function value
tail(tSNE_fit$itercosts, 1)

tSNE_new_test <- tSNE_fit$Y |>
  tibble::as_tibble(.name_repair = "unique")
names(tSNE_data) <- c("tSNE1", "tSNE2")


# PHATE simulate new test data and then compare training vs new predicted test

## To read tSNE for training data
phate_2NC7 <- read_rds("data/two_nonlinear/two_non_linear_diff_shaped_close_clusters_phate_knn_5.rds")

phate_training <- phate_2NC7 |>
  filter(ID %in% UMAP_d_2NC7_tr$ID)

## PHATE
knn <- 5

PHATE_data <- phate(df, knn = knn, verbose = TRUE)
PHATE_data <- as_tibble(PHATE_data$embedding)

names(PHATE_data) <- c("PHATE1", "PHATE2")


################################################################################

## Simulate new test data (outside the domain)

# New badly simulate outside domain of training and compare for best tSNE
